### 사고건 1개 저장
POST http://localhost:8080/api/incidents
Content-Type: application/json

{
  "brand": "MLB",
  "orderNo": "OD202606051234567",
  "trackingNo": "91956001852",
  "incidentType": "송장흐름없음",
  "status": "pending"
}

### 사고건 전체 목록 보기
GET http://localhost:8080/api/incidents

### id 1번 사고건 1개만 보기
GET http://localhost:8080/api/incidents/1

### id 1번 사고건 삭제
DELETE http://localhost:8080/api/incidents/1

### 테스트 사용자 만들기
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "loginId": "metam_juhi",
  "password": "pass1234",
  "name": "주휘인",
  "role": "metam"
}

### 로그인 시도 (성공해야 함)
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "loginId": "metam_juhi",
  "password": "pass1234"
}

### 로그인 시도 (비밀번호 틀림 - 실패해야 함)
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "loginId": "metam_juhi",
  "password": "wrong"
}

### 1. 마스터 계정 (본사 - 관리자)
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "loginId": "master",
  "password": "master1234",
  "name": "본사관리자",
  "role": "admin"
}

### 2. 메타엠 계정 (CS 접수자)
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "loginId": "metam",
  "password": "metam1234",
  "name": "메타엠담당",
  "role": "metam"
}

### 3. 로젠 계정 (택배사 검토자)
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "loginId": "logen",
  "password": "logen1234",
  "name": "로젠담당",
  "role": "logen"
}